
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
  - "pypy"
  - "pypy3"
install:
  - pip install pycrypto
  - pip install pyasn1
  - pip install pysnmp-mibs
  - pip install pysmi
  - python setup.py install
script:
  - sh runtests.sh
